# Manifest contains metadata about the driver. To learn about the different
# values in this manifest refer to:
#   https://github.com/bblfsh/sdk/blob/master/manifest/manifest.go

name = "C#"
language = "csharp"
aliases = ["C#"]
status = "beta"
features = ["ast", "uast", "roles"]
