package normalizer

import (
	"gopkg.in/bblfsh/sdk.v2/uast"
	"gopkg.in/bblfsh/sdk.v2/uast/role"

	. "gopkg.in/bblfsh/sdk.v2/uast/transformer"
	"gopkg.in/bblfsh/sdk.v2/uast/transformer/positioner"
)

// Native is the of list `transformer.Transformer` to apply to a native AST.
// To learn more about the Transformers and the available ones take a look to:
// https://godoc.org/gopkg.in/bblfsh/sdk.v2/uast/transformer
var Native = Transformers([][]Transformer{
	// The main block of transformation rules.
	{Mappings(Annotations...)},
	{
		// RolesDedup is used to remove duplicate roles assigned by multiple
		// transformation rules.
		RolesDedup(),
	},
}...)

// PreprocessCode is a special block of transformations that are applied at the end
// and can access original source code file. It can be used to improve or
// fix positional information.
//
// https://godoc.org/gopkg.in/bblfsh/sdk.v2/uast/transformer/positioner
var PreprocessCode = []CodeTransformer{
	positioner.FromOffset(),
	positioner.TokenFromSource{
		Types: []string{
			"SingleLineCommentTrivia",
			"SingleLineDocumentationCommentTrivia",
		},
	},
}

var Code []CodeTransformer // legacy stage, will be deprecated

// Annotations is a list of individual transformations to annotate a native AST with roles.
var Annotations = []Mapping{

	// Misc
	AnnotateType("internal-type", nil, role.Incomplete),
	AnnotateType("CompilationUnit", nil, role.File, role.Module),
	AnnotateType("Block", nil, role.Block),
	AnnotateType("LockStatement", nil, role. Statement, role.Block, role.Incomplete),
	AnnotateType("CheckedStatement_UncheckedStatement", nil, role.Block, role.Statement, role.Incomplete),
	AnnotateType("CheckedExpression_UncheckedExpression", nil, role.Block, role.Expression, role.Incomplete),
	AnnotateType("UnsafeStatement", nil, role.Block, role.Statement, role.Incomplete),
	AnnotateType("FixedStatement", nil, role.Declaration, role.Incomplete),
	AnnotateType("NamespaceDeclaration", nil, role.Block, role.Scope),
	AnnotateType("EventFieldDeclaration", nil, role.Declaration, role.Variable),
	AnnotateType("EventDeclaration", nil, role.Declaration, role.Variable),
	AnnotateType("ArrayType", nil, role.List, role.Incomplete),
	AnnotateType("ArrayRankSpecifier", nil, role.List, role.Incomplete),
	AnnotateType("BracketedArgumentList", nil, role.List, role.Value, role.Incomplete), // i in someaArray[i]
	AnnotateType("OmittedArraySizeExpression", nil, role.List, role.Expression, role.Incomplete),
	AnnotateType("ArrayCreationExpression", nil, role.List, role.Expression, role.Instance, role.Incomplete),
	AnnotateType("ImplicitArrayCreationExpression", nil, role.List, role.Expression, role.Value, role.Incomplete),
	AnnotateType("StackAllocArrayCreationExpression", nil, role.List, role.Expression, role.Instance, role.Incomplete),
	AnnotateType("ArrayInitializerExpression", nil, role.List, role.Expression, role.Instance, role.Incomplete),
	AnnotateType("ElementAccessExpression", nil, role.List, role.Value, role.Incomplete),
	AnnotateType("CastExpression", nil, role.Expression, role.Incomplete),
	AnnotateType("PredefinedType", nil, role.Incomplete, role.Declaration, role.Variable),
	AnnotateType("GenericName", nil, role.Identifier, role.Incomplete), // FIXME: get the role from the IdentifierToken child?
	AnnotateType("TypeArgumentList", nil, role.Argument, role.List, role.Instance, role.Incomplete), // generic <T,U> types on instantiation
	AnnotateType("TypeParameterList", nil, role.Argument, role.List, role.Incomplete), // generic <T,U> types on specification
	AnnotateType("TypeParameter", nil, role.Argument, role.Incomplete),
	AnnotateType("ObjectCreationExpression", nil, role.Type, role.Instance),
	AnnotateType("AnonymousObjectCreationExpression", nil, role.Type, role.Anonymous, role.Instance),
	AnnotateType("AnonymousObjectMemberDeclarator", nil, role.Type, role.Anonymous, role.Variable, role.Value),
	AnnotateType("CollectionInitializerExpression", nil, role.Incomplete, role.Value),
	AnnotateType("SimpleAssignmentExpression", nil, role.Assignment, role.Expression),
	AnnotateType("ConditionalExpression", nil, role.Expression, role.Condition),
	AnnotateType("ConditionalAccessExpression", nil, role.Expression, role.Condition, role.Not, role.Null, role.Incomplete),
	AnnotateType("MemberBindingExpression", nil, role.Expression, role.Qualified),
	AnnotateType("IncompleteMember", nil, role.Function, role.Incomplete),
	AnnotateType("SkippedTokensTrivia", nil, role.Incomplete),
	AnnotateType("AttributeList", nil, role.List, role.Incomplete),
	AnnotateType("AttributeArgumentList", nil, role.List, role.Argument, role.Incomplete),
	AnnotateType("Attribute", nil, role.Incomplete),
	AnnotateType("AttributeArgument", nil, role.Argument, role.Incomplete),
	AnnotateType("AttributeTargetSpecifier", nil, role.Argument, role.Incomplete),
	AnnotateType("PointerType", nil, role.Declaration, role.TakeAddress, role.Incomplete),

	// Literals and Literal tokens
	AnnotateType("NumericLiteralToken", nil, role.Value, role.Number, role.Literal),
	AnnotateType("CharacterLiteralToken", nil, role.Literal, role.Character),
	AnnotateType("StringLiteralToken", nil, role.Literal, role.String),
	AnnotateType("TrueKeyword", FieldRoles{"Value": {Rename: uast.KeyToken}}, role.Boolean, role.Literal),
	AnnotateType("FalseKeyword", FieldRoles{"Value": {Rename: uast.KeyToken}}, role.Boolean, role.Literal),
	AnnotateType("NumericLiteralExpression", nil, role.Expression, role.Number, role.Literal),
	AnnotateType("CharacterLiteralExpression", nil, role.Expression, role.Character, role.Literal),
	AnnotateType("StringLiteralExpression", nil, role.Literal, role.String, role.Expression),
	AnnotateType("InterpolatedStringExpression", nil, role.Expression, role.String, role.Incomplete),
	AnnotateType("InterpolatedStringText", nil, role.Literal, role.String, role.Incomplete),
	AnnotateType("Interpolation", nil, role.Expression, role.Value, role.Incomplete),
	AnnotateType("InterpolationAlignmentClause", nil, role.Expression, role.Incomplete),
	AnnotateType("InterpolationFormatClause", nil, role.Expression, role.Incomplete),
	AnnotateType("TrueLiteralExpression", nil, role.Literal, role.Boolean, role.Expression),
	AnnotateType("FalseLiteralExpression", nil, role.Literal, role.Boolean, role.Expression),
	AnnotateType("NullLiteralExpression", nil, role.Literal, role.Null, role.Expression),

	// LINQ
	AnnotateType("QueryExpression", nil, role.Expression, role.Incomplete),
	AnnotateType("QueryBody", nil, role.Expression, role.Body, role.Incomplete),
	AnnotateType("SelectClause", nil, role.Expression, role.Incomplete),
	AnnotateType("WhereClause", nil, role.Expression, role.Incomplete),
	AnnotateType("FromClause", nil, role.Expression, role.Incomplete),
	AnnotateType("OrderByClause", nil, role.Expression, role.Incomplete),
	AnnotateType("AscendingOrdering", nil, role.Expression, role.Incomplete),
	AnnotateType("DescendingOrdering", nil, role.Expression, role.Incomplete),

	// Calls
	AnnotateType("InvocationExpression", nil, role.Function, role.Call),
	AnnotateType("ArgumentList", nil, role.Function, role.Call, role.Argument, role.List),
	AnnotateType("Argument", nil, role.Function, role.Call, role.Argument),
	AnnotateType("NameColon", nil, role.Function, role.Call, role.Argument, role.Name),
	AnnotateType("SimpleMemberAccessExpression", nil, role.Qualified),

	// Tokens and "trivias"
	AnnotateType("AmpersandAmpersandToken", nil, role.Operator, role.Relational, role.And),
	AnnotateType("AmpersandEqualsToken", nil, role.Operator, role.And, role.Equal),
	AnnotateType("AmpersandToken", nil, role.Operator, role.Bitwise, role.And),
	AnnotateType("AsteriskEqualsToken", nil, role.Operator, role.Arithmetic, role.Multiply, role.Equal),
	AnnotateType("AsteriskToken", nil, role.Operator, role.Arithmetic, role.Multiply),
	AnnotateType("BarBarToken", nil, role.Operator, role.Relational, role.Or),
	AnnotateType("BarEqualsToken", nil, role.Operator, role.Bitwise, role.Or, role.Equal),
	AnnotateType("BarToken", nil, role.Operator, role.Bitwise, role.Or),
	AnnotateType("CaretEqualsToken", nil, role.Operator, role.Bitwise, role.Xor, role.Equal),
	AnnotateType("CaretToken", nil, role.Operator, role.Bitwise, role.Xor),
	AnnotateType("CloseBraceToken", nil, role.Incomplete),
	AnnotateType("CloseBracketToken", nil, role.Incomplete),
	AnnotateType("CloseParenToken", nil, role.Incomplete),
	AnnotateType("ColonToken", nil, role.Incomplete),
	AnnotateType("CommaToken", nil, role.Incomplete),
	AnnotateType("DotToken", nil, role.Incomplete),
	AnnotateType("EndOfFileToken", nil, role.Noop, role.Incomplete),
	AnnotateType("EqualsEqualsToken", nil, role.Operator, role.Relational, role.Equal),
	AnnotateType("EqualsGreaterThanToken", nil, role.Operator, role.Relational, role.GreaterThanOrEqual),
	AnnotateType("EqualsToken", nil, role.Operator, role.Equal),
	AnnotateType("ExclamationEqualsToken", nil, role.Operator, role.Relational, role.Not, role.Equal),
	AnnotateType("ExclamationToken", nil, role.Operator, role.Not),
	AnnotateType("GreaterThanEqualsToken", nil, role.Operator, role.Relational, role.GreaterThanOrEqual),
	AnnotateType("GreaterThanGreaterThanEqualsToken", nil, role.Operator, role.Bitwise, role.RightShift, role.Equal),
	AnnotateType("GreaterThanGreaterThanToken", nil, role.Operator, role.Bitwise, role.RightShift),
	AnnotateType("GreaterThanToken", nil, role.Operator, role.Relational, role.GreaterThan),
	AnnotateType("InterpolatedStringEndToken", nil, role.Incomplete, role.String),
	AnnotateType("InterpolatedStringStartToken", nil, role.Incomplete, role.String),
	AnnotateType("InterpolatedStringTextToken", nil, role.Incomplete, role.String),
	AnnotateType("LessThanEqualsToken", nil, role.Operator, role.Relational, role.LessThanOrEqual),
	AnnotateType("LessThanLessThanEqualsToken", nil, role.Operator, role.Bitwise, role.LeftShift, role.Equal),
	AnnotateType("LessThanLessThanToken", nil, role.Operator, role.Bitwise, role.LeftShift),
	AnnotateType("LessThanToken", nil, role.Operator, role.Relational, role.LessThan),
	AnnotateType("MinusEqualsToken", nil, role.Operator, role.Arithmetic, role.Substract, role.Equal),
	AnnotateType("MinusGreaterThanToken", nil, role.Operator, role.Dereference),
	AnnotateType("PointerMemberAccess", nil, role.Dereference, role.Type, role.Name),
	AnnotateType("MinusMinusToken", nil, role.Operator, role.Unary, role.Decrement),
	AnnotateType("MinusToken", nil, role.Operator, role.Arithmetic, role.Substract),
	AnnotateType("OmittedArraySizeExpressionToken", nil, role.Incomplete),
	AnnotateType("OpenBraceToken", nil, role.Incomplete),
	AnnotateType("OpenBracketToken", nil, role.Incomplete),
	AnnotateType("OpenParenToken", nil, role.Incomplete),
	AnnotateType("PercentEqualsToken", nil, role.Operator, role.Arithmetic, role.Modulo, role.Equal),
	AnnotateType("PercentToken", nil, role.Operator, role.Arithmetic, role.Modulo),
	AnnotateType("PlusEqualsToken", nil, role.Operator, role.Arithmetic, role.Add, role.Equal),
	AnnotateType("PlusPlusToken", nil, role.Unary, role.Arithmetic, role.Increment),
	AnnotateType("PlusToken", nil, role.Operator, role.Arithmetic, role.Substract),
	AnnotateType("QuestionQuestionToken", nil, role.Operator, role.Incomplete),
	AnnotateType("QuestionToken", nil, role.Operator, role.Incomplete),
	AnnotateType("SemicolonToken", nil, role.Incomplete),
	AnnotateType("SlashEqualsToken", nil, role.Operator, role.Arithmetic, role.Divide, role.Equal),
	AnnotateType("SlashToken", nil, role.Operator, role.Arithmetic, role.Divide),
	AnnotateType("TildeToken", nil, role.Operator, role.Unary, role.Bitwise, role.Not),

	// Keywords: we probably need a role.Keyword for languages like this that add a specific node for them
	AnnotateType("None", nil, role.Incomplete), // e.g. SemiColonField or lines not ended in ;
	AnnotateType("UsingKeyword", FieldRoles{"Value": {Rename: uast.KeyToken}}, role.Import, role.Incomplete),
	AnnotateType("AbstractKeyword", FieldRoles{"Value": {Rename: uast.KeyToken}}, role.Incomplete),
	AnnotateType("AddKeyword", FieldRoles{"Value": {Rename: uast.KeyToken}}, role.Incomplete),
	AnnotateType("AsKeyword", FieldRoles{"Value": {Rename: uast.KeyToken}}, role.Incomplete),
	AnnotateType("AscendingKeyword", FieldRoles{"Value": {Rename: uast.KeyToken}}, role.Incomplete),
	AnnotateType("AssemblyKeyword", FieldRoles{"Value": {Rename: uast.KeyToken}}, role.Incomplete),
	AnnotateType("AsyncKeyword", FieldRoles{"Value": {Rename: uast.KeyToken}}, role.Incomplete),
	AnnotateType("AwaitKeyword", FieldRoles{"Value": {Rename: uast.KeyToken}}, role.Incomplete),
	AnnotateType("BaseKeyword", FieldRoles{"Value": {Rename: uast.KeyToken}}, role.Incomplete),
	AnnotateType("BoolKeyword", FieldRoles{"Value": {Rename: uast.KeyToken}}, role.Boolean, role.Declaration),
	AnnotateType("BreakKeyword", FieldRoles{"Value": {Rename: uast.KeyToken}}, role.Break),
	AnnotateType("ByteKeyword", FieldRoles{"Value": {Rename: uast.KeyToken}}, role.Number, role.Declaration),
	AnnotateType("CaseKeyword", FieldRoles{"Value": {Rename: uast.KeyToken}}, role.Switch, role.Case),
	AnnotateType("CharKeyword", FieldRoles{"Value": {Rename: uast.KeyToken}}, role.Character, role.Declaration),
	AnnotateType("CheckedKeyword", FieldRoles{"Value": {Rename: uast.KeyToken}}, role.Incomplete),
	AnnotateType("ClassKeyword", FieldRoles{"Value": {Rename: uast.KeyToken}}, role.Type, role.Declaration),
	AnnotateType("ConstKeyword", FieldRoles{"Value": {Rename: uast.KeyToken}}, role.Declaration, role.Incomplete),
	AnnotateType("DecimalKeyword", FieldRoles{"Value": {Rename: uast.KeyToken}}, role.Number, role.Declaration),
	AnnotateType("DefaultKeyword", FieldRoles{"Value": {Rename: uast.KeyToken}}, role.Default),
	AnnotateType("DelegateKeyword", FieldRoles{"Value": {Rename: uast.KeyToken}}, role.Incomplete),
	AnnotateType("DoKeyword", FieldRoles{"Value": {Rename: uast.KeyToken}}, role.Incomplete),
	AnnotateType("DoubleKeyword", FieldRoles{"Value": {Rename: uast.KeyToken}}, role.Number, role.Declaration),
	AnnotateType("ElseKeyword", FieldRoles{"Value": {Rename: uast.KeyToken}}, role.Else),
	AnnotateType("EnumKeyword", FieldRoles{"Value": {Rename: uast.KeyToken}}, role.Incomplete),
	AnnotateType("EventKeyword", FieldRoles{"Value": {Rename: uast.KeyToken}}, role.Incomplete),
	AnnotateType("ExplicitKeyword", FieldRoles{"Value": {Rename: uast.KeyToken}}, role.Incomplete),
	AnnotateType("ExternKeyword", FieldRoles{"Value": {Rename: uast.KeyToken}}, role.Incomplete),
	AnnotateType("FixedKeyword", FieldRoles{"Value": {Rename: uast.KeyToken}}, role.Incomplete),
	AnnotateType("FloatKeyword", FieldRoles{"Value": {Rename: uast.KeyToken}}, role.Number, role.Declaration),
	AnnotateType("ForKeyword", FieldRoles{"Value": {Rename: uast.KeyToken}}, role.For),
	AnnotateType("FromKeyword", FieldRoles{"Value": {Rename: uast.KeyToken}}, role.Incomplete),
	AnnotateType("GetKeyword", FieldRoles{"Value": {Rename: uast.KeyToken}}, role.Incomplete),
	AnnotateType("GotoKeyword", FieldRoles{"Value": {Rename: uast.KeyToken}}, role.Goto),
	AnnotateType("IfKeyword", FieldRoles{"Value": {Rename: uast.KeyToken}}, role.If),
	AnnotateType("ImplicitKeyword", FieldRoles{"Value": {Rename: uast.KeyToken}}, role.Incomplete),
	AnnotateType("InKeyword", FieldRoles{"Value": {Rename: uast.KeyToken}}, role.Incomplete),
	AnnotateType("IntKeyword", FieldRoles{"Value": {Rename: uast.KeyToken}}, role.Number, role.Declaration),
	AnnotateType("InterfaceKeyword", FieldRoles{"Value": {Rename: uast.KeyToken}}, role.Incomplete),
	AnnotateType("InternalKeyword", FieldRoles{"Value": {Rename: uast.KeyToken}}, role.Incomplete),
	AnnotateType("IsKeyword", FieldRoles{"Value": {Rename: uast.KeyToken}}, role.Incomplete),
	AnnotateType("LockKeyword", FieldRoles{"Value": {Rename: uast.KeyToken}}, role.Incomplete),
	AnnotateType("LongKeyword", FieldRoles{"Value": {Rename: uast.KeyToken}}, role.Number, role.Declaration),
	AnnotateType("NamespaceKeyword", FieldRoles{"Value": {Rename: uast.KeyToken}}, role.Block),
	AnnotateType("NewKeyword", FieldRoles{"Value": {Rename: uast.KeyToken}}, role.Instance),
	AnnotateType("NullKeyword", FieldRoles{"Value": {Rename: uast.KeyToken}}, role.Null, role.Literal),
	AnnotateType("ObjectKeyword", FieldRoles{"Value": {Rename: uast.KeyToken}}, role.Type, role.Incomplete),
	AnnotateType("OperatorKeyword", FieldRoles{"Value": {Rename: uast.KeyToken}}, role.Incomplete),
	AnnotateType("OrderByKeyword", FieldRoles{"Value": {Rename: uast.KeyToken}}, role.Incomplete),
	AnnotateType("OverrideKeyword", FieldRoles{"Value": {Rename: uast.KeyToken}}, role.Incomplete),
	AnnotateType("ParamsKeyword", FieldRoles{"Value": {Rename: uast.KeyToken}}, role.Incomplete),
	AnnotateType("PartialKeyword", FieldRoles{"Value": {Rename: uast.KeyToken}}, role.Incomplete),
	AnnotateType("PrivateKeyword", FieldRoles{"Value": {Rename: uast.KeyToken}}, role.Visibility, role.Instance),
	AnnotateType("ProtectedKeyword", FieldRoles{"Value": {Rename: uast.KeyToken}}, role.Visibility, role.Subtype),
	AnnotateType("PublicKeyword", FieldRoles{"Value": {Rename: uast.KeyToken}}, role.Visibility, role.World),
	AnnotateType("ReadOnlyKeyword", FieldRoles{"Value": {Rename: uast.KeyToken}}, role.Incomplete),
	AnnotateType("RemoveKeyword", FieldRoles{"Value": {Rename: uast.KeyToken}}, role.Incomplete),
	AnnotateType("ReturnKeyword", FieldRoles{"Value": {Rename: uast.KeyToken}}, role.Return),
	AnnotateType("SByteKeyword", FieldRoles{"Value": {Rename: uast.KeyToken}}, role.Number, role.Declaration),
	AnnotateType("SealedKeyword", FieldRoles{"Value": {Rename: uast.KeyToken}}, role.Incomplete),
	AnnotateType("SelectKeyword", FieldRoles{"Value": {Rename: uast.KeyToken}}, role.Incomplete),
	AnnotateType("SetKeyword", FieldRoles{"Value": {Rename: uast.KeyToken}}, role.Incomplete),
	AnnotateType("ShortKeyword", FieldRoles{"Value": {Rename: uast.KeyToken}}, role.Number, role.Declaration),
	AnnotateType("SizeOfKeyword", FieldRoles{"Value": {Rename: uast.KeyToken}}, role.Incomplete),
	AnnotateType("StackAllocKeyword", FieldRoles{"Value": {Rename: uast.KeyToken}}, role.Incomplete),
	AnnotateType("StaticKeyword", FieldRoles{"Value": {Rename: uast.KeyToken}}, role.Incomplete),
	AnnotateType("StringKeyword", FieldRoles{"Value": {Rename: uast.KeyToken}}, role.String, role.Declaration),
	AnnotateType("StructKeyword", FieldRoles{"Value": {Rename: uast.KeyToken}}, role.Type, role.Declaration),
	AnnotateType("SwitchKeyword", FieldRoles{"Value": {Rename: uast.KeyToken}}, role.Switch),
	AnnotateType("ThisKeyword", FieldRoles{"Value": {Rename: uast.KeyToken}}, role.Incomplete),
	AnnotateType("ThrowKeyword", FieldRoles{"Value": {Rename: uast.KeyToken}}, role.Incomplete),
	AnnotateType("TypeOfKeyword", FieldRoles{"Value": {Rename: uast.KeyToken}}, role.Incomplete),
	AnnotateType("UIntKeyword", FieldRoles{"Value": {Rename: uast.KeyToken}}, role.Number, role.Declaration),
	AnnotateType("ULongKeyword", FieldRoles{"Value": {Rename: uast.KeyToken}}, role.Number, role.Declaration),
	AnnotateType("UShortKeyword", FieldRoles{"Value": {Rename: uast.KeyToken}}, role.Number, role.Declaration),
	AnnotateType("UncheckedKeyword", FieldRoles{"Value": {Rename: uast.KeyToken}}, role.Incomplete),
	AnnotateType("UnsafeKeyword", FieldRoles{"Value": {Rename: uast.KeyToken}}, role.Incomplete),
	AnnotateType("UsingKeyword", FieldRoles{"Value": {Rename: uast.KeyToken}}, role.Incomplete),
	AnnotateType("VirtualKeyword", FieldRoles{"Value": {Rename: uast.KeyToken}}, role.Incomplete),
	AnnotateType("VoidKeyword", FieldRoles{"Value": {Rename: uast.KeyToken}}, role.Incomplete),
	AnnotateType("VolatileKeyword", FieldRoles{"Value": {Rename: uast.KeyToken}}, role.Incomplete),
	AnnotateType("WhereKeyword", FieldRoles{"Value": {Rename: uast.KeyToken}}, role.Incomplete),
	AnnotateType("WhileKeyword", FieldRoles{"Value": {Rename: uast.KeyToken}}, role.While),
	AnnotateType("YieldKeyword", FieldRoles{"Value": {Rename: uast.KeyToken}}, role.Return, role.Incomplete),

	AnnotateType("IdentifierToken", FieldRoles{"Value": {Rename: uast.KeyToken}},
		role.Identifier, role.Expression),
	AnnotateType("QualifiedName", nil, role.Qualified, role.Identifier),

	// Binary/Unary expressions
	AnnotateType("BinaryExpression_BitwiseAndExpression", nil, role.Binary, role.Expression,
		role.Bitwise, role.And),
	AnnotateType("BinaryExpression_BitwiseOrExpression", nil, role.Binary, role.Expression,
		role.Bitwise, role.And),
	AnnotateType("BinaryExpression_BitwiseNotExpression", nil, role.Binary, role.Expression,
		role.Bitwise, role.Not),
	AnnotateType("BinaryExpression_ExclusiveOrExpression", nil, role.Binary, role.Expression,
		role.Bitwise, role.And),
	AnnotateType("BinaryExpression_LeftShiftExpression", nil, role.Binary, role.Expression,
		role.Bitwise, role.LeftShift),
	AnnotateType("BinaryExpression_RightShiftExpression", nil, role.Binary, role.Expression,
		role.Bitwise, role.LeftShift),
	AnnotateType("PrefixUnaryExpression_BitwiseNotExpression", nil, role.Unary, role.Expression,
		role.Bitwise, role.Not),

	AnnotateType("PrefixUnaryExpression_LogicalNotExpression", nil, role.Unary, role.Expression,
		role.Relational, role.Not),
	AnnotateType("BinaryExpression_NotEqualsExpression", nil, role.Binary, role.Expression,
		role.Relational, role.Not, role.Equal),
	AnnotateType("BinaryExpression_LessThanExpression", nil, role.Binary, role.Expression,
		role.Relational, role.LessThan),
	AnnotateType("BinaryExpression_LessThanOrEqualExpression", nil, role.Binary, role.Expression,
		role.Relational, role.LessThanOrEqual),
	AnnotateType("BinaryExpression_GreaterThanExpression", nil, role.Binary, role.Expression,
		role.Relational, role.GreaterThanOrEqual),
	AnnotateType("BinaryExpression_GreaterThanOrEqualExpression", nil, role.Binary, role.Expression,
		role.Relational, role.GreaterThanOrEqual),
	AnnotateType("BinaryExpression_LogicalAndExpression", nil, role.Binary, role.Expression,
		role.Relational, role.Or),
	AnnotateType("BinaryExpression_LogicalOrExpression", nil, role.Binary, role.Expression,
		role.Relational, role.Or),
	AnnotateType("BinaryExpression_EqualsExpression", nil, role.Binary, role.Expression,
		role.Relational, role.Equal),

	AnnotateType("BinaryExpression_AddExpression", nil, role.Binary, role.Expression,
		role.Arithmetic, role.Add),
	AnnotateType("BinaryExpression_SubtractExpression", nil, role.Binary, role.Expression,
		role.Arithmetic, role.Substract),
	AnnotateType("BinaryExpression_ModuloExpression", nil, role.Binary, role.Expression,
		role.Arithmetic, role.Modulo),
	AnnotateType("BinaryExpression_MultiplyExpression", nil, role.Binary, role.Expression,
		role.Arithmetic, role.Multiply),
	AnnotateType("BinaryExpression_DivideExpression", nil, role.Binary, role.Expression,
		role.Arithmetic, role.Divide),
	AnnotateType("PrefixUnaryExpression_PostIncrementExpression", nil, role.Unary, role.Expression,
		role.Arithmetic, role.Increment),
	AnnotateType("PrefixUnaryExpression_PostDecrementExpression", nil, role.Unary, role.Expression,
		role.Arithmetic, role.Decrement),
	AnnotateType("PostfixUnaryExpression_PostIncrementExpression", nil, role.Unary, role.Expression,
		role.Arithmetic, role.Increment, role.Postfix),
	AnnotateType("PostfixUnaryExpression_PostDecrementExpression", nil, role.Unary, role.Expression,
		role.Arithmetic, role.Decrement, role.Postfix),
	AnnotateType("PrefixUnaryExpression_PreIncrementExpression", nil, role.Unary, role.Expression,
		role.Arithmetic, role.Increment),
	AnnotateType("PrefixUnaryExpression_PreDecrementExpression", nil, role.Unary, role.Expression,
		role.Arithmetic, role.Decrement),
	AnnotateType("PostfixUnaryExpression_PreIncrementExpression", nil, role.Unary, role.Expression,
		role.Arithmetic, role.Increment, role.Postfix),
	AnnotateType("PostfixUnaryExpression_PreDecrementExpression", nil, role.Unary, role.Expression,
		role.Arithmetic, role.Decrement, role.Postfix),
	AnnotateType("PrefixUnaryExpression_UnaryPlusExpression", nil, role.Unary, role.Positive),
	AnnotateType("PrefixUnaryExpression_UnaryMinusExpression", nil, role.Unary, role.Negative),
	AnnotateType("PrefixUnaryExpression_AddressOfExpression", nil, role.Unary, role.TakeAddress),
	AnnotateType("PrefixUnaryExpression_PointerIndirectionExpression", nil, role.Unary, role.Dereference),
	AnnotateType("PointerMemberAccessExpression", nil, role.Operator, role.Dereference),

	AnnotateType("BinaryExpression_AsExpression", nil, role.Expression, role.Binary, role.Alias, role.Incomplete),
	AnnotateType("BinaryExpression_IsExpression", nil, role.Expression, role.Binary, role.Condition, role.Equal),
	AnnotateType("BinaryExpression_CoalesceExpression", nil, role.Expression, role.Binary, role.Condition, role.Not, role.Null),
	AnnotateType("BaseExpression", nil, role.Expression, role.Type, role.Base, role.Call),
	AnnotateType("IsPatternExpression", nil, role.Expression, role.Condition, role.Equal),
	AnnotateType("ConstantPattern", nil, role.Value, role.Incomplete),
	AnnotateType("DeclarationPattern", nil, role.Expression, role.Incomplete),
	AnnotateType("TypeOfExpression", nil, role.Expression, role.Incomplete),
	AnnotateType("DefaultExpression", nil, role.Expression, role.Value, role.Default),
	AnnotateType("DefaultLiteralExpression", nil, role.Expression, role.Value, role.Literal, role.Default),
	AnnotateType("ConstructorConstraint", nil, role.Type, role.Function, role.Declaration, role.Argument, role.Incomplete),
	AnnotateType("ClassOrStructConstraint_StructConstraint", nil, role.Type, role.Function, role.Declaration, role.Argument, role.Incomplete),
	AnnotateType("ClassOrStructConstraint_ClassConstraint", nil, role.Type, role.Function, role.Declaration, role.Argument, role.Incomplete),
	AnnotateType("CheckedStatement", nil, role.Block, role.Incomplete),
	AnnotateType("CheckedExpression", nil, role.Expression, role.Incomplete),
	AnnotateType("AwaitExpression", nil, role.Expression, role.Incomplete),
	AnnotateType("SizeOfExpression", nil, role.Expression, role.Number, role.Value, role.Incomplete),
	AnnotateType("NullableType", nil, role.Expression, role.Type, role.Null),

	// Other expressions
	AnnotateType("DeclarationExpression", nil, role.Declaration, role.Expression),
	AnnotateType("SingleVariableDesignation", nil, role.Declaration, role.Name, role.Variable),
	AnnotateType("ParenthesizedExpression", nil, role.Expression),
	AnnotateType("LocalDeclarationStatement", nil, role.Declaration, role.Expression),
	AnnotateType("VariableDeclaration", nil, role.Declaration, role.Variable, role.Expression),
	AnnotateType("VariableDeclarator", nil, role.Declaration, role.Variable, role.Right),
	AnnotateType("NameEquals", nil, role.Assignment, role.Right),
	AnnotateType("EqualsValueClause", nil, role.Assignment, role.Right),
	AnnotateType("ExpressionStatement", nil, role.Expression, role.Statement),
	AnnotateType("ThrowStatement", nil, role.Statement, role.Throw),
	AnnotateType("ThrowExpression", nil, role.Expression, role.Throw),
	AnnotateType("AddAssignmentExpression", nil, role.Assignment, role.Expression, role.Add),
	AnnotateType("SubtractAssignmentExpression", nil, role.Assignment, role.Expression, role.Substract),
	AnnotateType("MultiplyAssignmentExpression", nil, role.Assignment, role.Expression, role.Multiply),
	AnnotateType("DivideAssignmentExpression", nil, role.Assignment, role.Expression, role.Divide),
	AnnotateType("ModuloAssignmentExpression", nil, role.Assignment, role.Expression, role.Modulo),
	AnnotateType("LeftShiftAssignmentExpression", nil, role.Assignment, role.Expression, role.LeftShift),
	AnnotateType("RightShiftAssignmentExpression", nil, role.Assignment, role.Expression, role.RightShift),
	AnnotateType("AndAssignmentExpression", nil, role.Assignment, role.Expression, role.And),
	AnnotateType("ExclusiveOrAssignmentExpression", nil, role.Assignment, role.Expression, role.Xor),
	AnnotateType("OrAssignmentExpression", nil, role.Assignment, role.Expression, role.Or),


	// Types and methods
	AnnotateType("ClassDeclaration", nil, role.Type, role.Declaration),
	AnnotateType("InterfaceDeclaration", nil, role.Type, role.Declaration),
	AnnotateType("ExplicitInterfaceSpecifier", nil, role.Type, role.Name),
	AnnotateType("StructDeclaration", nil, role.Type, role.Declaration),
	AnnotateType("EnumDeclaration", nil, role.Type, role.Declaration, role.Enumeration),
	AnnotateType("EnumMemberDeclaration", nil, role.Type, role.Declaration, role.Enumeration, role.Value),
	AnnotateType("TupleExpression", nil, role.Value, role.List, role.Expression),
	AnnotateType("TupleType", nil, role.Declaration, role.List, role.Expression),
	AnnotateType("TupleElement", nil, role.List, role.Value),
	AnnotateType("BaseConstructorInitializer", nil, role.Function, role.Declaration, role.Argument, role.Base, role.Initialization, role.Incomplete),
	AnnotateType("BaseList", nil, role.Base, role.List),
	AnnotateType("SimpleBaseType", nil, role.Base, role.Type),
	AnnotateType("ConstructorDeclaration", nil, role.Type, role.Function, role.Declaration, role.This),
	AnnotateType("DestructorDeclaration", nil, role.Type, role.Function, role.Declaration, role.Incomplete),
	AnnotateType("FieldDeclaration", nil, role.Type, role.Declaration, role.Variable),
	AnnotateType("MethodDeclaration", nil, role.Type, role.Function, role.Declaration),
	AnnotateType("UsingDirective", nil, role.Import, role.Statement),
	AnnotateType("IdentifierName", nil, role.Identifier), // FIXME: get the token from the IdentifierToken child?
	AnnotateType("ParameterList", nil, role.Function, role.Declaration, role.Argument, role.List),
	AnnotateType("Parameter", nil, role.Function, role.Declaration, role.Argument),
	AnnotateType("ReturnStatement", nil, role.Statement, role.Return),
	AnnotateType("YieldStatement_YieldReturnStatement", nil, role.Statement, role.Return, role.Incomplete),
	AnnotateType("YieldStatement_YieldBreakStatement", nil, role.Statement, role.Break, role.Incomplete),
	AnnotateType("SimpleLambdaExpression", nil, role.Function, role.Declaration, role.Anonymous, role.Expression),
	AnnotateType("ParenthesizedLambdaExpression", nil, role.Function, role.Declaration, role.Anonymous, role.Expression),
	AnnotateType("AnonymousMethodExpression", nil, role.Function, role.Declaration, role.Anonymous, role.Expression),
	AnnotateType("ThisExpression", nil, role.Expression, role.This),
	AnnotateType("TypeParameterConstraintClause", nil, role.Function, role.Declaration, role.Argument, role.Condition, role.Incomplete),
	AnnotateType("TypeConstraint", nil, role.Function, role.Declaration, role.Argument, role.Condition, role.Type, role.Name, role.Incomplete),
	AnnotateType("ObjectInitializerExpression", nil, role.Type, role.Instance, role.Call, role.Block),
	AnnotateType("PropertyDeclaration", nil, role.Function, role.Value, role.Declaration, role.Incomplete),
	AnnotateType("AccessorList", nil, role.List, role.Function, role.Declaration, role.Incomplete),
	AnnotateType("AddAccessorDeclaration", nil, role.Function, role.Declaration, role.Value, role.Incomplete),
	AnnotateType("RemoveAccessorDeclaration", nil, role.Function, role.Declaration, role.Value, role.Incomplete),
	AnnotateType("GetAccessorDeclaration", nil, role.Function, role.Declaration, role.Value, role.Incomplete),
	AnnotateType("SetAccessorDeclaration", nil, role.Function, role.Declaration, role.Value, role.Incomplete),
	AnnotateType("ArrowExpressionClause", nil, role.Function, role.Body, role.Block),
	// inner function
	AnnotateType("LocalFunctionStatement", nil, role.Function, role.Declaration, role.Scope, role.Incomplete),
	// indexer declarations
	AnnotateType("IndexerDeclaration", nil, role.Function, role.Declaration, role.List, role.Incomplete),
	// indexer declaration [arguments]
	AnnotateType("BracketedParameterList", nil, role.Function, role.Declaration, role.List, role.Argument),
	AnnotateType("ConversionOperatorDeclaration", nil, role.Function, role.Declaration, role.Operator),
	AnnotateType("DelegateDeclaration", nil, role.Function, role.Declaration, role.Incomplete),

	// Flow control
	AnnotateType("WhileStatement", nil, role.While, role.Statement),
	AnnotateType("DoStatement", nil, role.DoWhile, role.Statement),
	AnnotateType("SwitchStatement", nil, role.Switch, role.Statement),
	AnnotateType("SwitchSection", nil, role.Switch, role.Block),
	AnnotateType("CaseSwitchLabel", nil, role.Switch, role.Case, role.Name),
	AnnotateType("DefaultSwitchLabel", nil, role.Switch, role.Case, role.Default),
	AnnotateType("ForStatement", nil, role.For, role.Statement),
	AnnotateType("IfStatement", nil, role.If, role.Statement),
	AnnotateType("ElseClause", nil, role.Else, role.Statement),
	AnnotateType("BreakStatement", nil, role.Break, role.Statement),
	AnnotateType("ContinueStatement", nil, role.Break, role.Statement),
	AnnotateType("GotoStatement", nil, role.Goto, role.Statement),
	AnnotateType("LabeledStatement", nil, role.Block, role.Statement, role.Incomplete),
	AnnotateType("EmptyStatement", nil, role.Statement, role.Noop),

	// Preprocessor
	AnnotateType("LineDirectiveTrivia", nil, role.Noop, role.Incomplete),
	AnnotateType("PragmaWarningDirectiveTrivia", nil, role.Noop, role.Incomplete),
	AnnotateType("WarningDirectiveTrivia", nil, role.Noop, role.Incomplete),
	AnnotateType("ErrorDirectiveTrivia", nil, role.Noop, role.Incomplete),
	AnnotateType("PragmaChecksumDirectiveTrivia", nil, role.Noop, role.Incomplete),
	AnnotateType("RegionDirectiveTrivia", nil, role.Block, role.Incomplete),
	AnnotateType("EndRegionDirectiveTrivia", nil, role.Block, role.Noop, role.Incomplete),
	AnnotateType("IfDirectiveTrivia", nil, role.If, role.Block, role.Incomplete),
	AnnotateType("ElifDirectiveTrivia", nil, role.Else, role.If, role.Block, role.Incomplete),
	AnnotateType("ElseDirectiveTrivia", nil, role.Else, role.Block, role.Incomplete),
	AnnotateType("EndIfDirectiveTrivia", nil, role.If, role.Block, role.Noop, role.Incomplete),
	AnnotateType("DefineDirectiveTrivia", nil, role.Declaration, role.Value, role.Incomplete),
	AnnotateType("UndefDirectiveTrivia", nil, role.Declaration, role.Value, role.Incomplete),
	AnnotateType("DisabledTextTrivia", nil, role.Noop, role.Incomplete),

	// Comments
	AnnotateType("SingleLineCommentTrivia", nil, role.Comment, role.Noop),
	AnnotateType("SingleLineDocumentationCommentTrivia", nil, role.Comment, role.Noop, role.Documentation),
}
